FriendsV2/FriendsV2/Models/BuildUser.cs
using System;
using System.Collections.Generic;

namespace FriendsV2.Models
{
    public partial class BuildUser
    {
        public BuildUser()
        {
            MailMessagesFromProfile = new HashSet<MailMessages>();
            MailMessagesToProfile = new HashSet<MailMessages>();
            ModList = new HashSet<ModList>();
        }

        public int Id { get; set; }
        public string Displayname { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Bio { get; set; }
        public string UserAccountId { get; set; }
        public string PhotoPath { get; set; }

        public ICollection<MailMessages> MailMessagesFromProfile { get; set; }
        public ICollection<MailMessages> MailMessagesToProfile { get; set; }
        public ICollection<ModList> ModList { get; set; }
    }
}

FriendsV2/FriendsV2/Controllers/BuildTablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using FriendsV2.Models;

namespace FriendsV2.Controllers
{
    public class BuildTablesController : Controller
    {
        private readonly MinecraftV2Context _context;
        private UserManager<IdentityUser> _userManager;
        private IHostingEnvironment _webroot;

        public BuildTablesController(MinecraftV2Context context, UserManager<IdentityUser> userManager, IHostingEnvironment webroot )
        {
            _context = context;
            _userManager = userManager;
            _webroot = webroot;
        }

        [Authorize]
        public IActionResult List()
        {
            IEnumerable<BuildTable> posts = _context.BuildTable.ToList<BuildTable>();
            return View(posts);
        }

        public IActionResult BuildInfo(int id)
        {
            BuildTable buildTable = _context.BuildTable.Find(id);
            return View(buildTable);
        }

        // GET: BuildTables
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.BuildTable.ToListAsync());
        }

        // GET: BuildTables/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildTable = await _context.BuildTable
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buildTable == null)
            {
                return NotFound();
            }

            return View(buildTable);
        }

        // GET: BuildTables/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: BuildTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Buildname,BuildContent,BuildTime,BuilderNum,WorldSeed,BuildPhoto,BuildDate")] BuildTable buildTable, IFormFile FilePhoto)
        {
            if (FilePhoto.Length > 0)
            {
                string buildPhoto = _webroot.WebRootPath + "\\buildPhotos\\";
                var fileName = Path.GetFileName(FilePhoto.FileName);

                using (var stream = System.IO.File.Create(buildPhoto + fileName))
                {
                    await FilePhoto.CopyToAsync(stream);
                    buildTable.BuildPhoto = fileName;
                }
            }

            if (ModelState.IsValid)
            {
                _context.Add(buildTable);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }
            return View(buildTable);
        }

        // GET: BuildTables/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildTable = await _context.BuildTable.FindAsync(id);
            if (buildTable == null)
            {
                return NotFound();
            }
            return View(buildTable);
        }

        // POST: BuildTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Buildname,BuildContent,BuildTime,BuilderNum,WorldSeed,BuildPhoto,BuildDate")] BuildTable buildTable)
        {
            if (id != buildTable.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(buildTable);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BuildTableExists(buildTable.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(List));
            }
            return View(buildTable);
        }

        // GET: BuildTables/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildTable = await _context.BuildTable
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buildTable == null)
            {
                return NotFound();
            }

            return View(buildTable);
        }

        // POST: BuildTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var buildTable = await _context.BuildTable.FindAsync(id);
            _context.BuildTable.Remove(buildTable);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(List));
        }

        private bool BuildTableExists(int id)
        {
            return _context.BuildTable.Any(e => e.Id == id);
        }

    }
}

FriendsV2/FriendsV2/Controllers/BuildUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using FriendsV2.Models;

namespace FriendsV2.Controllers
{
    public class BuildUsersController : Controller
    {
        private readonly MinecraftV2Context _context;
        private UserManager<IdentityUser> _userManager;
        private IHostingEnvironment _webroot;

        public BuildUsersController(MinecraftV2Context context, UserManager<IdentityUser> userManager, IHostingEnvironment webroot )
        {
            _context = context;
            _userManager = userManager;
            _webroot = webroot;
        }

        [Authorize]
        public IActionResult ProfileInfo()
        {
            string userID = _userManager.GetUserId(User);
            BuildUser profile = _context.BuildUser.FirstOrDefault(p => p.UserAccountId == userID);

            if (profile == null)
            {
                return RedirectToAction("Create");
            }

            return View(profile);
        }

        // GET: BuildUsers
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.BuildUser.ToListAsync());
        }

        [Authorize]
        public async Task<IActionResult> Browse()
        {
            return View(await _context.BuildUser.ToListAsync());
        }

        // GET: BuildUsers/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildUser = await _context.BuildUser
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buildUser == null)
            {
                return NotFound();
            }

            return View(buildUser);
        }

        [Authorize]
        public async Task<IActionResult> Show(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildUser = await _context.BuildUser.FirstOrDefaultAsync(m => m.Id == id);

            if (buildUser == null)
            {
                return NotFound();
            }

            return View(buildUser);
        }

        // GET: BuildUsers/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: BuildUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Displayname,Firstname,Lastname,Bio,UserAccountId,PhotoPath")] BuildUser buildUser, IFormFile FilePhoto)
        {
            if (FilePhoto.Length > 0)
            {
                string photoPath = _webroot.WebRootPath + "\\userPhotos\\";
                var fileName = Path.GetFileName(FilePhoto.FileName);

                using (var stream = System.IO.File.Create(photoPath + fileName))
                {
                    await FilePhoto.CopyToAsync(stream);
                    buildUser.PhotoPath = fileName;
                }
            }

            if (ModelState.IsValid)
            {
                _context.Add(buildUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ProfileInfo));
            }
            return View(buildUser);
        }

        // GET: BuildUsers/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildUser = await _context.BuildUser.FindAsync(id);
            if (buildUser == null)
            {
                return NotFound();
            }
            return View(buildUser);
        }

        // POST: BuildUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Displayname,Firstname,Lastname,Bio,UserAccountId,PhotoPath")] BuildUser buildUser, IFormFile FilePhoto)
        {

            if (id != buildUser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(buildUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BuildUserExists(buildUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ProfileInfo));
            }
            return View(buildUser);
        }

        // GET: BuildUsers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildUser = await _context.BuildUser
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buildUser == null)
            {
                return NotFound();
            }

            return View(buildUser);
        }

        // POST: BuildUsers/Delete/5
        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var buildUser = await _context.BuildUser.FindAsync(id);
            _context.BuildUser.Remove(buildUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BuildUserExists(int id)
        {
            return _context.BuildUser.Any(e => e.Id == id);
        }
    }
}

FriendsV2/FriendsV2/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using FriendsV2.Models;
using FriendsV2.ViewModels;

namespace FriendsV2.Controllers
{
    public class MessagesController : Controller
    {
        private MinecraftV2Context _context;
        private UserManager<IdentityUser> _userManager;
        public MessagesController(MinecraftV2Context context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Inbox()
        {
            BuildUser profile = _context.BuildUser.FirstOrDefault(id =>
            id.UserAccountId == _userManager.GetUserId(User));

            InboxViewModel inbox = new InboxViewModel();
            inbox.mailMessages = _context.MailMessages.Where(to => to.ToProfileId == profile.Id).ToList();

            List<BuildUser> fromList = new List<BuildUser>();
            foreach (var msg in inbox.mailMessages)
            {
                fromList.Add(_context.BuildUser.FirstOrDefault(from => from.Id == msg.FromProfileId));
            }
            inbox.fromProfile = fromList;
            return View(inbox);
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NewMessage(int id)
        {
            ViewBag.ToProfileId = id;
            return View();
        }

        public IActionResult Read(int id)
        {
            MailMessages mail = _context.MailMessages.FirstOrDefault(m => m.Id == id);
            mail.IsRead = true;
            _context.Update(mail);
            _context.SaveChanges();
            return View(mail);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Send([Bind("MessageTitle, MessageText")] MailMessages mail, int toProfileId)
        {
            BuildUser fromUser = _context.BuildUser.FirstOrDefault(p => p.UserAccountId == _userManager.GetUserId(User));
            mail.FromProfileId = fromUser.Id;
            mail.IsRead = false;
            mail.FromProfile = fromUser;
            mail.ToProfileId = toProfileId;

            _context.Add(mail);
            _context.SaveChanges();

            return RedirectToAction("Browse", "BuildUsers");
        }
    }
}

FriendsV2/FriendsV2/Views/BuildUsers/Browse.cshtml
@model IEnumerable<FriendsV2.Models.BuildUser>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Displayname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhotoPath)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Displayname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhotoPath)
            </td>
            <td>
                <a asp-action="Show" asp-route-id="@item.Id">Show</a> |
            </td>
        </tr>
}
    </tbody>
</table>

FriendsV2/FriendsV2/Views/BuildUsers/Create.cshtml
@using Microsoft.AspNetCore.Identity;
@inject UserManager<IdentityUser> userManager
@model FriendsV2.Models.BuildUser

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>BuildUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Displayname" class="control-label"></label>
                <input asp-for="Displayname" class="form-control" />
                <span asp-validation-for="Displayname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Firstname" class="control-label"></label>
                <input asp-for="Firstname" class="form-control" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lastname" class="control-label"></label>
                <input asp-for="Lastname" class="form-control" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bio" class="control-label"></label>
                <input asp-for="Bio" class="form-control" />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserAccountId" class="control-label"></label>
                <input asp-for="UserAccountId" class="form-control" value="@userManager.GetUserId(User)" />
                <span asp-validation-for="UserAccountId" class="text-danger"></span>
            </div>
            <div>
                <label for="Photo"></label>
                <input id="FilePhoto" type="file" name="FilePhoto" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ProfileInfo">Go to Profile</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FriendsV2/FriendsV2/Views/BuildUsers/Delete.cshtml
@model FriendsV2.Models.BuildUser

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BuildUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Displayname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Displayname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Bio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserAccountId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserAccountId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhotoPath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhotoPath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FriendsV2/FriendsV2/Views/BuildUsers/Details.cshtml
@model FriendsV2.Models.BuildUser

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>BuildUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Displayname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Displayname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Bio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserAccountId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserAccountId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhotoPath)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhotoPath)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FriendsV2/FriendsV2/Views/BuildUsers/Edit.cshtml
@model FriendsV2.Models.BuildUser

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>BuildUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Displayname" class="control-label"></label>
                <input asp-for="Displayname" class="form-control" />
                <span asp-validation-for="Displayname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Firstname" class="control-label"></label>
                <input asp-for="Firstname" class="form-control" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lastname" class="control-label"></label>
                <input asp-for="Lastname" class="form-control" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bio" class="control-label"></label>
                <input asp-for="Bio" class="form-control" />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserAccountId" class="control-label"></label>
                <input asp-for="UserAccountId" class="form-control" />
                <span asp-validation-for="UserAccountId" class="text-danger"></span>
            </div>
            <div>
                <label for="Photo"></label>
                <input id="FilePhoto" type="file" name="FilePhoto" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FriendsV2/FriendsV2/Views/BuildUsers/ProfileInfo.cshtml
@model FriendsV2.Models.BuildUser

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Friends on the Block</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Discords">Discords</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Builds
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                        <a class="dropdown-item" asp-controller="BuildTables" asp-action="List">Posts</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        My Messages
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                        <a class="dropdown-item" asp-area="" asp-controller="Messages" asp-action="Inbox">Inbox</a>
                        <a class="dropdown-item" asp-area="" asp-controller="Messages" asp-action="NewMessage">Send Messages</a>
                        <a class="dropdown-item" asp-area="" asp-controller="Messages" asp-action="Read">Read</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="About">About</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="BuildUsers" asp-action="ProfileInfo">My Profile</a>
                </li>
                <partial name="_LoginPartial" />
            </ul>
        </div>
    </div>
</nav>

<h2>Profile</h2>

<div>
    <h4>@Html.DisplayFor(model => model.Displayname)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            <img src="~/userPhotos/@Html.DisplayFor(model => model.PhotoPath)" width="200" height="200" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Displayname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Displayname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Bio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserAccountId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserAccountId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-controller="Home" asp-action="Index">Back to Home</a>
</div>

FriendsV2/FriendsV2/Views/BuildUsers/Show.cshtml
@model FriendsV2.Models.BuildUser

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Profile</h2>

<div>
    <h4>Builder @Html.DisplayFor(model => model.Displayname)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dd>
            <img src="~/userPhotos/@Html.DisplayFor(model => model.PhotoPath)" width="200" height="200" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Displayname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Displayname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Bio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bio)
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>